### ISSUE TITLE
`make docs` doesn't work from the start

### ISSUE THREAD

**Issue by eddiebergman** [automl/automl_template#13]
Running make docs leads to a weird sphinx error I've never seen which is basically saying it can't even give an error. I suspect it is coming from automl-sphinx-theme but I'm not certain.

@renesass 

```bash
$ make docs
make -C docs docs
make[1]: Entering directory '/home/skantify/code/mf-prior-bench/docs'
SPHINX_GALLERY_PLOT=False sphinx-build -b html  .  build/html
Running Sphinx v5.1.1
WARNING: logo file 'images/logo.png' does not exist
WARNING: favicon file 'images/favicon.ico' does not exist

Exception occurred:
  File "/home/skantify/.pyenv/versions/3.8.10/lib/python3.8/sre_parse.py", line 598, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
re.error: bad character range r-b at position 29
The full traceback has been saved in /tmp/sphinx-err-tc691ppe.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make[1]: *** [Makefile:13: html] Error 2
make[1]: Leaving directory '/home/skantify/code/mf-prior-bench/docs'
make: *** [Makefile:73: docs] Error 2
```

```bash
$ pip list | grep sphinx
automl-sphinx-theme           0.1.12
sphinx-autodoc-typehints      1.19.2
sphinx-gallery                0.11.0
sphinx-jinja2-compat          0.1.2
sphinx-prompt                 1.5.0
sphinx-tabs                   3.4.0
sphinx-toolbox                3.1.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
```

The output of the `.log` file
```python
$ cat /tmp/sphinx-err-0fnz53e_.log
# Sphinx version: 5.1.1
# Python version: 3.8.10 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.0.3
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/skantify/code/mf-prior-bench/.venv/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/skantify/code/mf-prior-bench/.venv/lib/python3.8/site-packages/sphinx/application.py", line 258, in __init__
    self._post_init_env()
  File "/home/skantify/code/mf-prior-bench/.venv/lib/python3.8/site-packages/sphinx/application.py", line 317, in _post_init_env
    self.env.find_files(self.config, self.builder)
  File "/home/skantify/code/mf-prior-bench/.venv/lib/python3.8/site-packages/sphinx/environment/__init__.py", line 362, in find_files
    self.project.discover(exclude_paths, self.config.include_patterns)
  File "/home/skantify/code/mf-prior-bench/.venv/lib/python3.8/site-packages/sphinx/project.py", line 39, in discover
    for filename in get_matching_files(
  File "/home/skantify/code/mf-prior-bench/.venv/lib/python3.8/site-packages/sphinx/util/matching.py", line 122, in get_matching_files
    exclude_matchers = compile_matchers(exclude_patterns)
  File "/home/skantify/code/mf-prior-bench/.venv/lib/python3.8/site-packages/sphinx/util/matching.py", line 57, in compile_matchers
    return [re.compile(_translate_pattern(pat)).match for pat in patterns]
  File "/home/skantify/code/mf-prior-bench/.venv/lib/python3.8/site-packages/sphinx/util/matching.py", line 57, in <listcomp>
    return [re.compile(_translate_pattern(pat)).match for pat in patterns]
  File "/home/skantify/.pyenv/versions/3.8.10/lib/python3.8/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/home/skantify/.pyenv/versions/3.8.10/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/home/skantify/.pyenv/versions/3.8.10/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/home/skantify/.pyenv/versions/3.8.10/lib/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/home/skantify/.pyenv/versions/3.8.10/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/home/skantify/.pyenv/versions/3.8.10/lib/python3.8/sre_parse.py", line 598, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
re.error: bad character range r-b at position 29
```

**Comment by renesass** [comment]
I ran into the same issues but I still don't know why they are happening. I actually changed that one line in my python source directly and then everything worked as expected. But yeah, that's no solution. 

Keep you updated.

**Comment by renesass** [comment]
I just expanded the tests and they are all successful:
https://github.com/automl/automl_sphinx_theme/pull/10
